Added Center widget
Securrency-OSS/mirai pull request #102
Opened 2023-04-04 18:05 UTC by vinothvino42

## Description

In this PR, I added a center mirai parser and added an example route for the center widget in the mirai gallery app.

## Related Issues

NONE

## Type of Change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-04-05 13:21 UTC, divyanshub024 requested changes

2023-04-05 13:21 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/icon_utils.dart
> +  'format_align_center': Icons.format_align_center,
I think this icon is already there.

2023-04-05 14:10 UTC, vinothvino42 commented on packages/mirai/lib/src/utils/icon_utils.dart
> +  'format_align_center': Icons.format_align_center,
@divyanshub024 Ohh sorry, I removed it. Can you check it again?

2023-04-06 09:24 UTC, divyanshub024 requested changes
@vinothvino42 Thanks for amazing work 💯 

Please check my comments.

2023-04-06 09:24 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/center_example.json
> +                "onPressed": {}
Can we remove the `onPressed` here? As the container does not take onpressed.

2023-04-06 09:24 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/center_example.json
> +        "type": "container",
Can we remove this container so child is always in the center of the screen?

2023-04-06 15:48 UTC, vinothvino42 commented on examples/mirai_gallery/assets/json/center_example.json
> +                "onPressed": {}
My bad, I just copied and pasted from another example. I'll fix it now.

2023-04-06 15:50 UTC, vinothvino42 commented on examples/mirai_gallery/assets/json/center_example.json
> +        "type": "container",
I added it for showing how the center widget's `widthFactor` and `heightFactor` property works. Okay, I'll remove it and push the code now.

2023-04-07 06:18 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/center_example.json
> +                "onPressed": {}
Thank you!!

2023-04-07 06:19 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/center_example.json
> +        "type": "container",
Hmm, it's better to remove it. Bcz people might run it in a web/desktop app and while resizing it's good to see the widget resize as well.

2023-04-07 07:51 UTC, vinothvino42 commented on examples/mirai_gallery/assets/json/center_example.json
> +        "type": "container",
Okay, I'll remove the top Container widget and widthFactor and heightFactor from the Center widget.

2023-04-07 08:08 UTC, DivyanshuBhargavaSecurrency approved these changes

2023-04-07 08:10 UTC, merged