Added InputValidation support in Mirai TextFormField
Securrency-OSS/mirai pull request #106
Opened 2023-04-07 12:17 UTC by iamasimkhan

## Description

Added `InputValidation` support in Mirai `TextFormField`

## Related Issues

Closes #105 

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-04-13 11:17 UTC, divyanshub024 requested changes

2023-04-13 11:17 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/text_field_example.json
> +                                "message": "Enter your correct phone number"
Can we change the message to "Enter a valid phone number?"

2023-04-13 11:17 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/text_field_example.json
> +                                "message": "The password should be correct"
Can we change the message to "Enter a valid password"

2023-04-13 11:17 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +  static final RegExp validFirstLastName = RegExp(r"^[A-Za-z .`'/-]{2,32}$");
All these variables should have common naming practice.

2023-04-13 11:17 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +  static bool validate(String value, String rule) {
Can we move this function to the enum class?

2023-04-13 11:17 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_text_validation/mirai_text_validation.dart
> +class MiraiTextValidation with _$MiraiTextValidation {
I think the right name should be `MiraiFormFieldValidator`

2023-04-13 11:17 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +  atleastFiveChars,
Can we remove these?

2023-04-13 12:20 UTC, iamasimkhan commented
Thanks for the comments, resolved all them now PR is ready.

2023-04-14 11:37 UTC, divyanshub024 requested changes

2023-04-14 11:37 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +RegExp notEmptyRegExp = RegExp("^[0-9a-zA-Z .`'/-]{1,50}\$");
Global variables are not a good idea. Can we move them inside the Enum class?

2023-04-14 11:37 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart
> +        }
Do we need try catch here?

2023-04-14 11:37 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +  notEmpty;
Can rename to isEmail, isPassword, isNotEmpty, etc.

2023-04-14 11:41 UTC, iamasimkhan commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart
> +        }
We are trying to convert String to an enum type value, which is very predictable to fail if we pass a string not one of the types.

2023-04-16 11:42 UTC, divyanshub024 commented on packages/mirai/lib/src/utils/input_validations.dart
> +  RegExp get _isNotEmptyRegExp => RegExp("^[0-9a-zA-Z .`'/-]{1,50}\$");
Why did we make it a getter function instead of a final variable? 

Does the getter have more benefit over a variable 🤔

2023-04-16 12:10 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart
> +        }
Cool

2023-04-16 16:58 UTC, iamasimkhan commented
It's breaking when we create a variable, ot compiles fine but fails once we run it on the device/emulator.

2023-04-17 07:22 UTC, divyanshub024 approved these changes

2023-04-17 07:23 UTC, merged