Added `Form` widget with `form-validation` support in `Mirai`
Securrency-OSS/mirai pull request #110
Opened 2023-04-11 11:48 UTC by iamasimkhan

## Description

Added `Form` widget with `form-validation` support in `Mirai`

## Related Issues

Closes #107 

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-04-13 10:17 UTC, iamasimkhan commented on examples/mirai_gallery/assets/json/form_example.json
> +                            "type": "elevatedButton",
Added this example page to highlight the `Form` with its child

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/lib/src/action/mirai_action_parser.dart
> +          if (Form.of(context).validate()) {
Performing validation action here once there is a `Form` widget in ascendants

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/lib/src/parsers/mirai_form/cubit/cubit/mirai_form_cubit.dart
> +  void addController(Map<String, TextEditingController> controller) {
Managing text edit controllers for all the textfields inside the form widget.

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/lib/src/parsers/mirai_form/cubit/cubit/mirai_form_state.dart
> +  final Map<String, TextEditingController> controllers;
Just the editing controllers

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.dart
> +    required String key,
Uniquely identifying text fields, can be named better!!

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart
> +    try {
If this is under the form widget, then we need to update the FormState, by adding the controller into the state.

2023-04-13 10:17 UTC, iamasimkhan commented on packages/mirai/pubspec.yaml
> +  flutter_bloc: ^8.1.2
flutter bloc library for state management is added.

2023-04-28 09:54 UTC, i-asimkhan commented on packages/mirai/lib/src/action/mirai_action_parser.dart
> +          if (Form.of(context).validate()) {
The following error appears when we try to use `Form.of(context).validate()` without builder. 

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Form.of() was called with a context that does not contain a Form widget.
No Form widget ancestor could be found starting from the context that was passed to Form.of(). This can happen because you are using a widget that looks for a Form ancestor, but no such ancestor exists.
```

2023-05-06 12:37 UTC, RodolfoSilva reviewed
I've also create a issue about a way to disable buttons and text fields when the form is in submiting mode. 
#119

2023-05-06 12:37 UTC, RodolfoSilva commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.dart
> +    required String key,
Following the web, i think this could be `name` or `fieldName` instead.

2023-05-07 10:57 UTC, i-asimkhan commented
> I've also create a issue about a way to disable buttons and text fields when the form is in submiting mode. #119

@RodolfoSilva Thanks for reviewing this. Your comment regarding `key` https://github.com/Securrency-OSS/mirai/pull/110#discussion_r1186690969 makes a lot of sense and further, I can discuss this with @divyanshub024 but I am more interested in your bullet regarding button-disabling. It would be great if you elaborate more on this. 👍 👍

2023-05-26 09:41 UTC, RodolfoSilva commented
Sure, I think we can add support for signals, and add the ability to widgets or actions react for signals. Imagine you have a widget thats emit a signal like, submitting and you have a widgets that subscribes when a signal occurs and apply some changes. 

For example:

This widget emits a signal when the button is pressed:

```json
{
  "type": "elevatedButton",
  "child": {
    "type": "text",
    "data": "Submit"
  }, 
  "onPressed": {
    "actionType": "signal",
    "name": "Mirai/submitting",
    "data": {},
    "then": {
      // run another action after the signal is emitted
    }
  },
  // ... other properties
}
````

Then you have a widget that subscribes to this signal and apply some changes to the widget:

```json
{
  "type": "textFormField",
  "maxLines": 1,
  "obscureText": false,
  "onSignals": [
    {
      "name": "Mirai/submitting",
      "patch": {
        "readOnly": true,
        "enabled": false
      }
    }
  ],
  "readOnly": false,
  "enabled": true,
  // ... other properties
},
```

This will patch the properties to the widget when the signal is emitted, allowing you to create dynamic widgets that reacts to signals. Making the UI more dynamic and reactive.

Sorry for the delay @i-asimkhan , I was on vacation.

2023-05-26 10:03 UTC, i-asimkhan commented
> Sure, I think we can add support for signals, and add the ability to widgets or actions react for signals. Imagine you have a widget thats emit a signal like, submitting and you have a widgets that subscribes when a signal occurs and apply some changes.
> 
> For example:
> 
> This widget emits a signal when the button is pressed:
> 
> ```json
> {
>   "type": "elevatedButton",
>   "child": {
>     "type": "text",
>     "data": "Submit"
>   }, 
>   "onPressed": {
>     "actionType": "signal",
>     "name": "Mirai/submitting",
>     "data": {},
>     "then": {
>       // run another action after the signal is emitted
>     }
>   },
>   // ... other properties
> }
> ```
> 
> Then you have a widget that subscribes to this signal and apply some changes to the widget:
> 
> ```json
> {
>   "type": "textFormField",
>   "maxLines": 1,
>   "obscureText": false,
>   "onSignals": [
>     {
>       "name": "Mirai/submitting",
>       "patch": {
>         "readOnly": true,
>         "enabled": false
>       }
>     }
>   ],
>   "readOnly": false,
>   "enabled": true,
>   // ... other properties
> },
> ```
> 
> This will patch the properties to the widget when the signal is emitted, allowing you to create dynamic widgets that reacts to signals. Making the UI more dynamic and reactive.
> 
> The signal name, could be anithing defined by the user.
> 
> Sorry for the delay @i-asimkhan , I was on vacation.

That's a great illustration. Thank you 👍

2023-07-11 14:24 UTC, i-asimkhan commented
Hey @RodolfoSilva 
What are your suggestions about the `MiraiFrom` `@freezed` model class, would it better to follow flutter widget convention, like this 


```
@freezed
class MiraiForm with _$MiraiForm {
  const factory MiraiForm({
    MiraiAction? onChanged,
    AutovalidateMode? autovalidateMode,
    required Map<String, dynamic> child,
    
  }) = _MiraiForm;

  factory MiraiForm.fromJson(Map<String, dynamic> json) =>
      _$MiraiFormFromJson(json);
}
```

or we should make strict rules here by defining a list of child widgets (mainly form-inputs), 




```
@freezed
class MiraiForm with _$MiraiForm {
  const factory MiraiForm({
    required List<Map<String, dynamic>> children,
    required MiraiSubmitAction action,
    
  }) = _MiraiForm;

  factory MiraiForm.fromJson(Map<String, dynamic> json) =>
      _$MiraiFormFromJson(json);
}
```

2023-07-11 14:31 UTC, i-asimkhan commented
> Hey @RodolfoSilva What are your suggestions about the `MiraiFrom` `@freezed` model class, would it better to follow flutter widget convention, like this
> 
> ```
> @freezed
> class MiraiForm with _$MiraiForm {
>   const factory MiraiForm({
>     MiraiAction? onChanged,
>     AutovalidateMode? autovalidateMode,
>     required Map<String, dynamic> child,
>     
>   }) = _MiraiForm;
> 
>   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
>       _$MiraiFormFromJson(json);
> }
> ```
> 
> or we should make strict rules here by defining a list of child widgets (mainly form-inputs),
> 
> ```
> @freezed
> class MiraiForm with _$MiraiForm {
>   const factory MiraiForm({
>     required List<Map<String, dynamic>> children,
>     required MiraiSubmitAction action,
>     
>   }) = _MiraiForm;
> 
>   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
>       _$MiraiFormFromJson(json);
> }
> ```

Secondly, we need to partition business logic from the `MiraiAction` as it is becoming more and more detailed. 
One of the thoughts I have is to make a generic type of Action and then extend many other types of actions, just like you did in LsdAction [here](https://github.com/RodolfoSilva/lsd/blob/main/packages/lsd/lib/src/action/lsd_action.dart)


The problem with `@freezed` models is that we can use the language feature <extend>, so there is another possibility that we make whole new action for submit as you have in LSD called `MiraiFormSubmitAction` and use its own implementation to handle the form submission.

2023-07-13 16:47 UTC, RodolfoSilva commented
> Hey @RodolfoSilva What are your suggestions about the `MiraiFrom` `@freezed` model class, would it better to follow flutter widget convention, like this
> 
> ```
> @freezed
> class MiraiForm with _$MiraiForm {
>   const factory MiraiForm({
>     MiraiAction? onChanged,
>     AutovalidateMode? autovalidateMode,
>     required Map<String, dynamic> child,
>     
>   }) = _MiraiForm;
> 
>   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
>       _$MiraiFormFromJson(json);
> }
> ```
> 
> or we should make strict rules here by defining a list of child widgets (mainly form-inputs),
> 
> ```
> @freezed
> class MiraiForm with _$MiraiForm {
>   const factory MiraiForm({
>     required List<Map<String, dynamic>> children,
>     required MiraiSubmitAction action,
>     
>   }) = _MiraiForm;
> 
>   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
>       _$MiraiFormFromJson(json);
> }
> ```

@i-asimkhan I prefer the first approach. it's more composable than the second. It is closer to HTML form and Flutter Form. This allows the user to decide what kind of child to use. I understand that the second approach will by default have a column implementation.

2023-07-13 16:56 UTC, RodolfoSilva commented
> > Hey @RodolfoSilva What are your suggestions about the `MiraiFrom` `@freezed` model class, would it better to follow flutter widget convention, like this
> > ```
> > @freezed
> > class MiraiForm with _$MiraiForm {
> >   const factory MiraiForm({
> >     MiraiAction? onChanged,
> >     AutovalidateMode? autovalidateMode,
> >     required Map<String, dynamic> child,
> >     
> >   }) = _MiraiForm;
> > 
> >   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
> >       _$MiraiFormFromJson(json);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or we should make strict rules here by defining a list of child widgets (mainly form-inputs),
> > ```
> > @freezed
> > class MiraiForm with _$MiraiForm {
> >   const factory MiraiForm({
> >     required List<Map<String, dynamic>> children,
> >     required MiraiSubmitAction action,
> >     
> >   }) = _MiraiForm;
> > 
> >   factory MiraiForm.fromJson(Map<String, dynamic> json) =>
> >       _$MiraiFormFromJson(json);
> > }
> > ```
> 
> Secondly, we need to partition the business logic from the `MiraiAction` as it is becoming more and more detailed. One of the thoughts I have is to make a generic type of Action and then extend many other types of actions, just like you did in LsdAction [here](https://github.com/RodolfoSilva/lsd/blob/main/packages/lsd/lib/src/action/lsd_action.dart)
> 
> The problem with `@freezed` models is that we can use the language feature , so there is another possibility that we make whole new action for submit as you have in LSD called `MiraiFormSubmitAction` and use its own implementation to handle the form submission.

I totally agree. Such a move will unlock a wealth of possibilities and customization options. It will empower us to utilize any other navigation library, such as go_router, or to modify the existing implementation. Additionally, partitioning would enable us to relocate MiraiForm into a distinct package.

When I started building LSD, I was thinking about composability and customization being in the control of the user who is using the library.

2023-08-04 08:25 UTC, divyanshub024 requested changes

2023-08-04 12:42 UTC, i-asimkhan commented on packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.dart
> +    bool? obscureText,
Yeah, the idea is to use the suffix icon as a show/hide place for text input. So in order to operate the suffix icon with this functionality, we need to check the obscureText as a not null value, and in case of null value the suffix icon (if exists any in the JSON) will only operate as a display item, not the one with in-built functionality of show/hide

2023-08-05 13:37 UTC, divyanshub024 approved these changes

2023-08-05 13:38 UTC, merged