feat: Add flutter `Stack` support in `Mirai` #113
Securrency-OSS/mirai pull request #114
Opened 2023-04-20 07:47 UTC by loud-at-heart

## Description

According to official documentation, Stack is a widget that positions its children relative to the edges of its box.

This class is useful if you want to overlap several children in a simple way, for example having some text and an image, overlaid with a gradient and a button attached to the bottom.

In this PR, Mirai Stack has been added to parse Stack Parameter

## Related Issues

closes #113 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-04-20 08:00 UTC, loud-at-heart commented
@i-asimkhan Please do have a check on this

2023-04-21 11:29 UTC, i-asimkhan reviewed
Thanks @loud-at-heart It is awesome feature, please can you add an example for this widget just like this https://github.com/Securrency-OSS/mirai/blob/main/examples/mirai_gallery/assets/json/container_example.json

2023-04-21 11:29 UTC, i-asimkhan commented on packages/mirai/lib/src/parsers/mirai_stack/mirai_stack_parser.dart
> +  String get type => WidgetType.column.name;
We need to add a new widget type called stack and use it here.

2023-04-21 11:29 UTC, i-asimkhan commented on packages/mirai/lib/src/parsers/mirai_gradient/mirai_gradient.dart
> +
Can we please remove this extra line?

2023-04-22 04:25 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_gradient/mirai_gradient.dart
> +
The extra line has been removed

2023-04-22 04:26 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_stack/mirai_stack_parser.dart
> +  String get type => WidgetType.column.name;
New widgetType as stack has been added

2023-04-22 04:38 UTC, loud-at-heart commented
@i-asimkhan since stack and positioned go hand in hand so I have added support for positioned also. The examples have been added as per asked

2023-04-23 23:03 UTC, divyanshub024 requested changes
This is pretty great work 💯 
Please check my suggestions.

2023-04-23 23:03 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_stack/mirai_stack_parser.dart
> +            (value) => Mirai.fromJson(value, context) ?? const SizedBox(),
Can we remove the `comma(,)` from the end for better code formatting and readability?

2023-04-24 04:00 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_stack/mirai_stack_parser.dart
> +            (value) => Mirai.fromJson(value, context) ?? const SizedBox(),
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart reviewed
The changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned.dart
> +* TODO :: Add support for fromRelativeRect
If this method is necessary, then I will code for this?

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned_parser.dart
> +          child: Mirai.fromJson(model.child, context) ?? const Placeholder(),
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned_parser.dart
> +          child: Mirai.fromJson(model.child, context) ?? const Placeholder(),
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned_parser.dart
> +          child: Mirai.fromJson(model.child, context) ?? const Placeholder(),
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned_parser.dart
> +          child: Mirai.fromJson(model.child, context) ?? const Placeholder(),
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_positioned/mirai_positioned_parser.dart
> +          top: model.top,
The above params were added

2023-04-24 04:19 UTC, loud-at-heart commented on packages/mirai/lib/src/parsers/mirai_alignment/mirai_alignment.dart
> +  bottomEnd;
Changes have been made as per asked. A new file `MiraiAlignmentDirectional` has been implemented.

2023-04-24 04:19 UTC, loud-at-heart commented on examples/mirai_gallery/assets/json/home_screen.json
> +                    "style": "list",
Changes have been made as per asked

2023-04-24 04:19 UTC, loud-at-heart commented on examples/mirai_gallery/assets/json/home_screen.json
> +                        "align": "center",
Changes have been made as per asked

2023-04-24 07:40 UTC, divyanshub024 approved these changes
Looks great 🚀

2023-04-24 07:40 UTC, merged