feat: Added support for `pushNamed` in Mirai Navigation
Securrency-OSS/mirai pull request #159
Opened 2023-06-16 10:15 UTC by i-asimkhan

## Description

Added support for `pushNamed` in Mirai Navigation

## Related Issues

Closes #79 

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-06-24 12:24 UTC, RodolfoSilva approved these changes
LGTM!

2023-07-03 07:11 UTC, nattawat-s-finstable commented
I really need this feature :(

2023-07-03 11:19 UTC, divyanshub024 requested changes

2023-07-03 11:19 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/navigator_example.json
> +                        },
Do we need to show a dialog in the push navigation example or this example is for all navigation?

2023-07-03 11:19 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/navigator_example.json
> +                        }
Why are we navigating to same screen?

2023-07-03 11:19 UTC, divyanshub024 commented on packages/mirai/lib/src/navigation/mirai_navigator.dart
> +    T? arguments,
Where are we using the argument param?

2023-07-03 11:32 UTC, i-asimkhan commented on packages/mirai/lib/src/navigation/mirai_navigator.dart
> +    T? arguments,
According to documentation, it can be used like this, now added this support in **miraiAction**

 ```
arguments: <String, String>{
     'city': 'Paris',
      'country': 'France',
},

```

2023-07-03 11:40 UTC, i-asimkhan commented on examples/mirai_gallery/assets/json/navigator_example.json
> +                        },
Yes, basically trying to showcase all types of navigation in **MiraiNavigator**.

2023-07-03 11:43 UTC, i-asimkhan commented on examples/mirai_gallery/assets/json/navigator_example.json
> +                        }
The reason we are navigating to the same screen is, that in this special type of navigation, we taking use of **assetPath** instead of `named` hence it is better to use the asset path of the same screen instead of initiating a new flow. 
For instance, if we navigate to homeScreen path or any other example path it will become confusing because those paths list completely different user-flows.

2023-07-03 11:49 UTC, i-asimkhan commented on examples/mirai_gallery/assets/json/navigator_example.json
> +                        },
I won't suggest it because that is a complete showcasing of the types of dialogues, but here it is in the spectrum of navigation. We can remove it from here if it creates confusion but that one is totally fine.

2023-07-04 10:06 UTC, divyanshub024 requested changes

2023-07-04 10:06 UTC, divyanshub024 commented on packages/mirai/lib/src/navigation/mirai_navigator.dart
> +    } else if (widget != null) {
Is it necessary to check for this condition? In case of pop, the widget will be null.

2023-07-04 10:19 UTC, i-asimkhan commented on packages/mirai/lib/src/navigation/mirai_navigator.dart
> +    } else if (widget != null) {
Thanks that's a great point, now removed

2023-07-04 12:16 UTC, merged