[DRAFT] feat: Add Mirai Switch
Securrency-OSS/mirai pull request #207
Opened 2023-09-16 16:36 UTC by kushalmahapatro

## Description

Add support for switch in Mirai. 

This basically takes up an initial value and a listener onChanged. 
The state of the switch is being handled by `MiraiSwitchCubit`. 

This is a draft PR raised to confirm that we are following the right practices and to verify if this is the correct approach for handling the state.

### TBD
1. Type of switch (Material/Cupertino/ adaptive)
2. Override colors (Is this required, or it would be always forced to adapt to the theme)
3. Additional action `onChanged`. (network call / updating value in shared preference or storage etc.)

## Related Issues
feat: Add support for Switch in Mirai #168

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-09-16 16:39 UTC, kushalmahapatro commented
Hi @divyanshub024 , @i-asimkhan. 

First of all, it was great working on MIRAI and with no due time I was able to adde the support to have a `Switch` components. 

This is not the full implementation, there are some more addition, which has been added in the TBD section and also need to discuss on those points.

2023-09-18 06:03 UTC, i-asimkhan reviewed
Thank you very much for this @kushalmahapatro I have a few suggestions in the comments comparing other parts of the widgets parsers in MIrai.

2023-09-18 06:03 UTC, i-asimkhan commented on packages/mirai/lib/src/utils/widget_type.dart
> +  switchButton,
That's fine we can remove the comments from here. Thanks for the clarification.

2023-09-18 06:20 UTC, divyanshub024 requested changes
Thanks a lot, @kushalmahapatro for this PR. Please check my comments.

2023-09-18 06:20 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
Can we add all the Switch values? 

```
    required this.value,
    required this.onChanged,
    this.activeColor,
    this.activeTrackColor,
    this.inactiveThumbColor,
    this.inactiveTrackColor,
    this.activeThumbImage,
    this.onActiveThumbImageError,
    this.inactiveThumbImage,
    this.onInactiveThumbImageError,
    this.thumbColor,
    this.trackColor,
    this.trackOutlineColor,
    this.trackOutlineWidth,
    this.thumbIcon,
    this.materialTapTargetSize,
    this.dragStartBehavior = DragStartBehavior.start,
    this.mouseCursor,
    this.focusColor,
    this.hoverColor,
    this.overlayColor,
    this.splashRadius,
    this.focusNode,
    this.onFocusChange,
    this.autofocus = false,
```

2023-09-18 06:20 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/cubit/mirai_switch_cubit.dart
> +class MiraiSwitchCubit extends Cubit<MiraiSwitchState> {
Let's remove the cubit. We are planning to remove the bloc from the package.

2023-09-24 19:47 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/cubit/mirai_switch_cubit.dart
> +class MiraiSwitchCubit extends Cubit<MiraiSwitchState> {
Cubit has been removed and replaced with StatefulWidget

2023-09-24 19:47 UTC, kushalmahapatro commented on packages/mirai/lib/src/utils/widget_type.dart
> +  switchButton,
The comment has been removed.

2023-09-24 19:48 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch_parser.dart
> +    return BlocProvider(
Cubit is replaced with StatefulWidget

2023-09-24 19:54 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
Most of the params has been covered along with switchType ( material [default], adaptive, cupertino ). 
Havn't covered params like :
``` dart
focusNode,
onFocusChange,
mouseCursor (for adaptive and material),
onInactiveThumbImageError (for adaptive and material),
onActiveThumbImageError (for adaptive and material),
applyCupertinoTheme (for cupertino and adaptive)
```

2023-09-24 19:59 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
@divyanshub024 , @i-asimkhan 
Question: 
There are multiple optional params which can be added to the switch. 
Show we use up something like widget book/ story book (where we can implement knobs for these params and as per that we can also give out the option to copy/preview the respective switchButton json to build MiraiSwitch)

2023-09-25 06:04 UTC, i-asimkhan commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
@kushalmahapatro  You are saying that if there would be a JSON editor on one side and the Flutter widget preview on the other side for widgets JSON preview ?

2023-09-25 06:10 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
Yup, and also knobs, to play around with ex: (drop down for the enum values, color picker etc) and the json value updates as per the selected params. 

This idea came coz, we have many optional params, and using all of them in the example would be tedious task. 
With the knobs we can ensure that, all the params works as expected and also from the json value, we can copy and reuse in unit and widget test cases as well.

2023-09-25 06:18 UTC, i-asimkhan commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
That's great that you thought to that deep extent. We have something like this internally which is of course yet not ready for production but soon it will be available where we can drag/drop, upload files, and edit the app metadata.

2023-09-25 06:29 UTC, i-asimkhan approved these changes
Looks good, I have only one more comment. 👍 👍 👍

2023-09-25 06:29 UTC, i-asimkhan commented on examples/mirai_gallery/assets/json/home_screen.json
> +                },
can we move this in the alphabetical order just after `MiraiSizedBox`

2023-09-25 06:32 UTC, i-asimkhan requested changes
Blocked by review from @divyanshub024

2023-09-25 06:35 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +    Map<String, dynamic>? onChanged,
Yup, That the BYOD section (The builder part). But nice to know about the Builder,  as it would be really great. 

Then let me add all the params in the json and create MiraiSwitch from it.

2023-09-25 06:36 UTC, kushalmahapatro commented on examples/mirai_gallery/assets/json/home_screen.json
> +                },
Sure.

2023-09-25 11:51 UTC, divyanshub024 requested changes

2023-09-25 11:51 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/widget/mirai_switch_widget_state.dart
> +abstract class _MiraiSwitchWidgetState extends State<MiraiSwitchWidget> {
Hey, Do we need this sep state abstract class? What if add `initState` and `_changeValue` into the Mirai switch widget?

2023-09-25 11:51 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +}
What if we use Mirai Image instead?

2023-09-25 11:51 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +  }
What if we use Mirai icon instead? I support both material and Cupertino.

2023-09-25 11:51 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/home_screen.json
> +                },
+1

2023-09-25 12:15 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +}
As i remember, MiraiImage returns of the widget Image.network / Image.file / Image.asset and these are Stateful Widget. But here we require an ImageProvided.

2023-09-25 16:27 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +}
<img width="1074" alt="image" src="https://github.com/Securrency-OSS/mirai/assets/20181633/ef66adfb-8544-45ff-875d-b3191b41d68d">

2023-09-25 16:47 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +}
> <img alt="image" width="1074" src="https://user-images.githubusercontent.com/20181633/270410319-ef66adfb-8544-45ff-875d-b3191b41d68d.png">

We can use this and leverage the MiraiWidgets. 
``` dart
ImageProvider? _getImageProvider(MiraiImage? image) {
    if (image == null && (image?.src ?? '').isEmpty) return null;

    final Widget? widget = Mirai.fromJson(image!.toJson(), context);
    if (widget != null && widget is Image) {
      return widget.image;
    }
    
    return null;
  }
```

2023-09-25 16:50 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +  }
This is one of the way, what do you say? 
``` dart
  Icon? get thumbIconWidget {
    if (thumbIcon == null) return null;

    final Widget? widget = Mirai.fromJson(thumbIcon!.toJson(), context);
    if (widget != null && widget is Icon) {
      return widget;
    }

    return null;
  }
```

2023-09-26 09:57 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/widget/mirai_switch_widget_state.dart
> +abstract class _MiraiSwitchWidgetState extends State<MiraiSwitchWidget> {
Let's remove it so it will be consistent with the the other widgets

2023-09-26 10:17 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +}
This looks great.

2023-09-26 10:18 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
> +  }
💯

2023-09-26 10:27 UTC, kushalmahapatro commented on packages/mirai/lib/src/parsers/mirai_switch/widget/mirai_switch_widget_state.dart
> +abstract class _MiraiSwitchWidgetState extends State<MiraiSwitchWidget> {
Umm, ok

2023-09-26 10:28 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_switch/widget/mirai_switch_widget_state.dart
> +abstract class _MiraiSwitchWidgetState extends State<MiraiSwitchWidget> {
Thank you!!

2023-09-30 20:47 UTC, divyanshub024 approved these changes
@kushalmahapatro Thank you so much for this valuable PR. 💯 🙏🏻

2023-09-30 20:57 UTC, merged