feat: Replaced Image.network with CachedNetworkImage. #255
Securrency-OSS/mirai pull request #270
Opened 2024-02-28 12:08 UTC by yousufmyk

## Description

Replaced Image.network with CachedNetworkImage 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2024-02-28 12:13 UTC, divyanshub024 requested changes
Hey @yousufmyk 👋🏻 

Thank you for the amazing contribution. I have some suggestions, please check my comments.

2024-02-28 12:13 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_image/mirai_image_parser.dart
> +  //     );
Can we remove these unwanted comments?

2024-02-28 12:15 UTC, divyanshub024 commented
@yousufmyk There are some formatting issues in `mirai_image_parser` can you please check?

2024-02-28 12:23 UTC, yousufmyk commented
Done, You can check now

2024-02-28 13:07 UTC, yousufmyk commented
I see, I've tried fixing Dart formatting Issues. Hopefully, now it should work fine.

2024-02-28 13:12 UTC, yousufmyk commented
@divyanshub024  don’t know why this keeps failing I tried "dart format --set-exit-if-changed ." and it works but again getting an issue do you have any idea about this issue?

2024-02-28 13:34 UTC, divyanshub024 commented
@yousufmyk 
Can you try running the following commands?

Make sure you have Melos installed in your system:

```
dart pub global activate melos
```
And then run
```
1. melos clean
2. melos bs
3. melos format
```

2024-02-28 13:44 UTC, yousufmyk commented
@divyanshub024 Thank you for the suggestions!  appreciate you taking the time to help troubleshoot.

I've now installed Melos and run the commands you provide.

2024-02-28 13:46 UTC, yousufmyk commented
I can see it’s again failing but on my side it says "
melos run format
  └> melos exec -- "dart format ."
     └> SUCCESS" after running melos

2024-02-28 14:03 UTC, divyanshub024 commented
@yousufmyk Can you run `flutter pub get` in mirai_gallery? When I ran it `pubspec.lock` file showed some changes. Alternatively, you can also run `melos bs` from the root folder.

2024-03-01 09:23 UTC, divyanshub024 commented
> @yousufmyk Can you run `flutter pub get` in mirai_gallery? When I ran it `pubspec.lock` file showed some changes. Alternatively, you can also run `melos bs` from the root folder.

Hey @yousufmyk, Did it help?

2024-03-16 17:02 UTC, divyanshub024 commented
Closed by #289

2024-03-16 17:02 UTC, closed without merging