feat: Add support for Filled Button
Securrency-OSS/mirai pull request #274
Opened 2024-02-28 22:45 UTC by iampranabray

## Description

- Created a Mirai Filled Button Parser 
- Added example to the Mirai gallery 
- filled button json is added in assets file. different use case of filled button Screenshot is attached bellow .
![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 02 43 01](https://github.com/Securrency-OSS/mirai/assets/23743392/c7899100-49ae-4d85-aa9a-8dee225742e5)

## Related Issues

Closes #264 

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2024-02-28 23:39 UTC, divyanshub024 requested changes
Hey @iampranabray 👋🏻 

Once again, Thank you for such amazing contributions. 

I have some suggestions, please check my comments.

2024-02-28 23:39 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart
> +      style: model.style?.parseElevated(context),
We should not use the `parseElevated`. It is for the elevated button. Can we create one Filled Style parser?

2024-02-28 23:39 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart
> +      statesController: materialStatesController,
We don't need `focusNode` and `statesController` as of now. We can remove it :)

2024-02-29 06:24 UTC, iampranabray commented on packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart
> +      style: model.style?.parseElevated(context),
Ah mistaken. Sure I will replace ;)

2024-02-29 06:28 UTC, iampranabray commented on packages/mirai/lib/src/parsers/mirai_filled_button/mirai_filled_button_parser.dart
> +      statesController: materialStatesController,
Sure I will remove .

2024-02-29 19:49 UTC, divyanshub024 commented
@iampranabray Can you please resolve these conflicts?

2024-02-29 19:53 UTC, iampranabray commented
Yha sure

2024-02-29 19:54 UTC, iampranabray commented
> @iampranabray Can you please resolve these conflicts? 

Yha sure

2024-03-01 08:43 UTC, divyanshub024 approved these changes
Thank you for this amazing contribution @iampranabray 🎉

2024-03-01 08:43 UTC, merged