#282 Add Search Bar in Example Gallery App
Securrency-OSS/mirai pull request #293
Opened 2024-03-26 16:14 UTC by vkmaxcooldude

## Description

- Create a BLoC, `HomeBloc`, for state management
- Rewrite the Gallery screen, to integrate `HomeBloc`
- Update the JSON, to store a list of `ListTile`s 

## Related Issues

Closes #282 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2024-03-26 16:14 UTC, vkmaxcooldude commented
@divyanshub024 Requesting review

2024-04-01 14:16 UTC, divyanshub024 requested changes

2024-04-01 14:16 UTC, divyanshub024 commented on examples/mirai_gallery/lib/app/home/home_screen.dart
> +                SizedBox(height: 24.0 + MediaQuery.of(context).padding.bottom)
Can we remove this and add some padding to the listview?

2024-04-01 14:16 UTC, divyanshub024 commented on examples/mirai_gallery/lib/app/home/bloc/home_bloc.dart
> +class HomeBloc extends Bloc<HomeEvent, HomeState> {
I'm thinking it's better to change it to a Cubit. It will make it more readable and easier for the people coming in first time. What do you think?

2024-04-01 15:55 UTC, vkmaxcooldude commented on examples/mirai_gallery/lib/app/home/home_screen.dart
> +                SizedBox(height: 24.0 + MediaQuery.of(context).padding.bottom)
Sure. I think that should be doable.

2024-04-01 16:35 UTC, vkmaxcooldude commented on examples/mirai_gallery/lib/app/home/bloc/home_bloc.dart
> +class HomeBloc extends Bloc<HomeEvent, HomeState> {
Sure, if ease of understanding is a priority, then Cubit will be better than BLoC. Removing BLoC will not hinder anything, so it's okay.

2024-04-01 17:16 UTC, divyanshub024 commented on examples/mirai_gallery/lib/app/home/bloc/home_bloc.dart
> +class HomeBloc extends Bloc<HomeEvent, HomeState> {
Thanks

2024-04-01 17:16 UTC, divyanshub024 commented on examples/mirai_gallery/lib/app/home/home_screen.dart
> +                SizedBox(height: 24.0 + MediaQuery.of(context).padding.bottom)
Thanks

2024-04-01 18:19 UTC, vkmaxcooldude commented
@divyanshub024 Can you check?

2024-04-02 07:23 UTC, divyanshub024 approved these changes
Thank you @vkmaxcooldude for back to back contributions 💯

2024-04-02 07:23 UTC, merged