`ThemeData` integration and enabling dark/light mode in example app
Securrency-OSS/mirai pull request #76
Opened 2023-03-22 09:08 UTC by iamasimkhan

## Description

`ThemeData` integration and enabling dark/light mode in the example app.

## Related Issues

Closes #46 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-03-22 12:43 UTC, divyanshub024 requested changes
Thanks a lot, @iamasimkhan!! 💯 

Please check my comments.

2023-03-22 12:43 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_color_scheme/mirai_color_scheme.dart
> +  ColorScheme? get parse {
It will always return `ColorScheme`. So we can make is nonnullable.

2023-03-22 12:43 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_color_scheme/mirai_color_scheme.dart
> +      onSurface: onSurface.toColor ?? Colors.white,
Giving default while color is wrong. Can we change them to non-nullable.

2023-03-22 12:43 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/app_bar_example.json
> +                "color": "#ffffff"
Do we need these styles? I was thinking to leave it empty. So they will pick the default style.

2023-03-22 12:43 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/bottom_nav_bar_example.json
> +        "backgroundColor": "#4D00E9",
What if we send this color from theme?

2023-03-23 08:04 UTC, iamasimkhan commented on examples/mirai_gallery/assets/json/bottom_nav_bar_example.json
> +        "backgroundColor": "#4D00E9",
Yeah, now I have set the surface colour to this colour in the theme, and by default, app-bar takes the surface colour as the background colour.

2023-03-25 13:17 UTC, divyanshub024 requested changes

2023-03-25 13:17 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_material_color/mirai_material_color.dart
> +      900: shade900.toColor ?? Colors.white,
Instead of null check, can we add the null assertion (!)? Since all the shade colors are required.

2023-03-25 13:17 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_material_color/mirai_material_color.dart
> +      (primary.toColor ?? Colors.white).value,
Here as well

2023-03-25 13:17 UTC, divyanshub024 commented on packages/mirai/lib/src/framework/mirai_app.dart
> +import 'package:mirai/mirai.dart';
Please, undo these changes.

2023-03-25 13:17 UTC, divyanshub024 commented on examples/mirai_gallery/pubspec.yaml
> +publish_to: "none" # Remove this line if you wish to publish to pub.dev
Can we revert these changes? As Flutter recommends using single quotes.

2023-03-25 13:17 UTC, divyanshub024 commented on examples/mirai_gallery/pubspec.yaml
> +  sdk: ">=2.19.2 <3.0.0"
Can we revert these changes? As Flutter recommends using single quotes.

2023-03-25 13:17 UTC, divyanshub024 commented on examples/mirai_gallery/lib/app_theme/app_theme_state.dart
> +class AppThemeState extends Equatable {
Can we use `freezed` instead? I don't want to add a new lib just for 1 state class.

2023-03-25 13:17 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/tab_bar_example.json
> +                            "color": "#FC5632"
Is it possible to take these colors from themes?

2023-03-27 10:43 UTC, divyanshub024 approved these changes

2023-03-27 10:43 UTC, merged