Added support for `iconButtonTheme` in `MiraiTheme`
Securrency-OSS/mirai pull request #94
Opened 2023-03-31 07:52 UTC by iamasimkhan

## Description

Added support for `iconButtonTheme` in `MiraiTheme`

## Related Issues

Closes #86 

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-04-04 12:41 UTC, divyanshub024 requested changes

2023-04-04 12:41 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_button_style/mirai_button_style.dart
> +    double? iconSize,
Do we need this?

2023-04-06 09:31 UTC, divyanshub024 requested changes

2023-04-06 09:33 UTC, iamasimkhan commented on examples/mirai_gallery/assets/json/example_light_theme.json
> +    },
Just align them with the theme data model here https://github.com/Securrency-OSS/mirai/blob/2d7d2c809f9e7b1684b9156fb5db50a7c4bbe0c8/packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart#L39

2023-04-06 11:20 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/example_light_theme.json
> +    },
Got it

2023-04-06 11:20 UTC, divyanshub024 approved these changes
💯

2023-04-06 11:20 UTC, merged