Added support for `appBarTheme` in `MiraiTheme`
Securrency-OSS/mirai pull request #96
Opened 2023-03-31 11:36 UTC by iamasimkhan

## Description

Added support for `appBarTheme` in `MiraiTheme`

## Related Issues

Closes #83 

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

2023-05-30 11:02 UTC, divyanshub024 requested changes

2023-05-30 11:02 UTC, divyanshub024 commented on packages/mirai/lib/src/parsers/mirai_system_ui_olverlay_style/mirai_system_ui_olverlay_style.dart
> +import 'package:flutter/services.dart';
There is a typo in the file name.

2023-05-31 07:12 UTC, i-asimkhan commented on examples/mirai_gallery/assets/json/example_light_theme.json
> +    },
No, we are removing them from the app-bar example JSON after their inclusion here, so the idea is we are allowing users to actually see how theming takes effect in the **app bar** with just a change of colours in one place.

2023-05-31 09:22 UTC, divyanshub024 commented on examples/mirai_gallery/assets/json/example_light_theme.json
> +    },
Let's remove it as discussed.

2023-05-31 10:00 UTC, merged